# Production Application Configuration
application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production
  
server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  
logging:
  level: INFO
  format: json
  

  
development:
  mock_external_apis: true
  debug_mode: true
  cors_enabled: true

